# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# AndroidX
android.useAndroidX=true

# Kotlin code style
kotlin.code.style=official

# Enable non-transitive R classes
android.nonTransitiveRClass=true

# Disable Gradle daemon for CI/phone builds
org.gradle.daemon=false

# AGP 8.13 официально рекомендует максимум SDK 36; SDK 37 нужен для MIUIX

# Нативный aapt2 для aarch64 Termux (вместо x86_64 из maven)
android.aapt2FromMavenOverride=/data/data/com.termux/files/home/tools/bin/aapt2-custom/aapt2
